language: objective-c
matrix:
    include:
        - osx_image: xcode9.3beta

script:
    - xcodebuild build test -project Validator.xcodeproj -scheme Validator-iOS -destination "platform=iOS Simulator,name=iPhone X"

